# Generated by Django 6.1 on 2026-08-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_vault', '0003_spotifyaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
