# Generated by Django 6.1 on 2026-09-07 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_vault', '0004_album_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
